### ISSUE TITLE
Pod  nodeSelector

### ISSUE THREAD

**Issue by jbenassi** [yokawasa/kubectl-plugin-ssh-jumphost#22]
We run a mix of arch types, I think the ssh-jump pod is supposed to work on x86/amd64, as I can't get it to work on arm64, would you add an additional nodeSelector type:

  nodeSelector:
    "kubernetes.io/os": linux
    **"kubernetes.io/arch": "amd64"**

**Comment by yokawasa** [comment]
@jbenassi very sorry for super late response 🙏 

It's very fair to specify "kubernetes.io/arch" in nodeSelector. I'll update shortly

```bash
$ uname -m 
# output
arm64

$ docker run -d --name ssh-server -p 22 corbinu/ssh-server
# output
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Comment by yokawasa** [comment]
FYI, you can specify your own pod template with  `--pod-template <file>` option.

**Comment by yokawasa** [comment]
@jbenassi 

new 0.8.1 has been released where default pod template has `kubernetes.io/arch : amd64` in nodeSelector.
https://github.com/yokawasa/kubectl-plugin-ssh-jump/releases/tag/0.8.1

```
kubectl krew upgrade

kubectl krew list                
PLUGIN    VERSION
ssh-jump  v0.8.1 
```

Thank you for the request!!
