### ISSUE TITLE
In hybrid Windows/Linux clusters the sshjump pod can land on Windows nodes and fail

### ISSUE THREAD

**Issue by swgriffith** [yokawasa/kubectl-plugin-ssh-jumphost#8]
The pod deployment is missing a node selector for linux nodes, so in a hybrid cluster you can end up with sshjump failing to start because its scheduled to a windows node.

Fix would be to update the 'kubectl run' command in the plugin to deploy a manifest with a node selector.

**Comment by yokawasa** [comment]
@swgriffith PR #9 has been merged! I've release `0.5.0` which can be installed via `kubectl krew install ssh-jump`
I'm closing the issue 
Thank you so much for your contribution again!
